# Generated by Django 3.2.16 on 2022-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('companyName', models.CharField(max_length=100, verbose_name='Компания')),
                ('positionName', models.CharField(max_length=100, verbose_name='Должность')),
                ('hireDate', models.DateTimeField(verbose_name='Дата приёма')),
                ('fireDate', models.DateTimeField(default=None, verbose_name='Дата увольнения')),
                ('salary', models.IntegerField(verbose_name='Ставка, руб.')),
                ('fraction', models.IntegerField(verbose_name='Ставка, %')),
                ('base', models.IntegerField(verbose_name='База, руб.')),
                ('advance', models.IntegerField(verbose_name='Аванс, руб.')),
                ('by_hours', models.BooleanField(default=True, verbose_name='Почасовая оплата')),
            ],
        ),
    ]
