# Generated by Django 3.2.16 on 2022-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='employee',
        ),
        migrations.AlterField(
            model_name='staff',
            name='fireDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hireDate',
            field=models.DateField(verbose_name='Дата приёма'),
        ),
    ]
